@extends('layout.user')
@section('title', 'dashboard')
@section('formMateri', 'active')
@section('content')
    @include('sweetalert::alert')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card" style="border-radius:10px;box-shadow: rgba(136, 165, 191, 0.48) 6px 2px 16px 0px, rgba(255, 255, 255, 0.8) -6px -2px 16px 0px;">
                    <div class="card-body">
                        <h4 class="card-title">Edit Materi</h4>
                        <p class="card-description">
                            Materi
                        </p>
                        <!--alert berhasil daftar-->
                        @if (session()->has('success'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif

                        <form class="forms-sample" action="{{ route('updateMateri', ['id' => $materi->id]) }}"
                            method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group mb-3">
                                @error('nama_materi')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                                <label for="exampleInputName1">Nama/Judul Materi</label>
                                <input type="text" name="nama_materi" class="form-control" id="exampleInputName1"
                                    placeholder="Nama/Judul" value="{{ $materi->nama_materi }}">
                            <div class="form-group mt-3">
                                @error('tingkatan_pendidikan')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                                <label for="exampleInputName1">Tingkatan Pendidikan</label>
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input type="radio" class="form-check-input" name="tingkatan_pendidikan"
                                            id="optionsRadios1" value="SD" onchange="updateOptions()">
                                        Sekolah Dasar
                                    </label>
                                </div>
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input type="radio" class="form-check-input" name="tingkatan_pendidikan"
                                            id="optionsRadios2" value="SMP" checked onchange="updateOptions()">
                                        Sekolah Menengah Keatas
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                @error('kelas')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                                <label for="exampleSelectKelas">Kelas</label>
                                <select class="form-control" name="kelas" id="selectKelas">
                                    {{-- Options will be generated by JavaScript --}}
                                </select>
                            </div>

                            <script>
                                function updateOptions() {
                                    var pendValue = document.querySelector('input[name="tingkatan_pendidikan"]:checked').value;
                                    var selectKelas = document.getElementById("selectKelas");
                                    selectKelas.innerHTML = ""; // Clear existing options

                                    if (pendValue === "SD") {
                                        // Add options 1-6 for SD
                                        for (var i = 1; i <= 6; i++) {
                                            var option = document.createElement("option");
                                            option.text = i;
                                            option.value = i;
                                            selectKelas.add(option);
                                        }
                                    } else if (pendValue === "SMP") {
                                        // Add options 1-3 for SMP
                                        for (var i = 1; i <= 3; i++) {
                                            var option = document.createElement("option");
                                            option.text = i;
                                            option.value = i;
                                            selectKelas.add(option);
                                        }
                                    }
                                }

                                // Call updateOptions() function when the page loads to ensure correct options are displayed initially
                                updateOptions();
                            </script>


                            <div class="form-group">
                                @error('tipe_materi')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                                <label for="exampleSelectGender">Tipe Materi</label>
                                <select class="form-control" name="tipe_materi" id="exampleSelectGender">
                                    <option value="dokumen">Dokumen</option>
                                    <option value="gambar">Gambar</option>
                                    <option value="video">Video</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Topik</label>
                                <select class="js-example-basic-multiple w-100" name="topik[]" multiple="multiple">
                                    <option value="topik1">Topik 1</option>
                                    <option value="topik2">Topik 2</option>
                                    <option value="topik3">Topik 3</option>
                                </select>
                            </div>
                            {{-- <div class="form-group">
                        <div class="form-check">
                          <label class="form-check-label">
                            <input type="checkbox" name="topik" value="1" class="form-check-input">
                            Topik 1
                          </label>
                        </div>
                        <div class="form-check">
                          <label class="form-check-label">
                            <input type="checkbox" name="topik" value="2" class="form-check-input" checked>
                            Topik 2
                          </label>
                        </div>
                      </div> --}}
                            <div class="form-group">
                                @error('file')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                                <label>File upload</label>
                                <input type="file" name="file" class="file-upload-default" value="{{ $materi->file }}">
                                <div class="input-group col-xs-12">
                                    <input type="text" class="form-control file-upload-info" disabled
                                        placeholder="Upload File" >
                                    <span class="input-group-append">
                                        <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                                    </span>
                                </div>
                            </div>
                            <div class="form-group">
                                @error('thumbnail')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                                <label>Thumbnail</label>
                                <input type="file" name="thumbnail" class="file-upload-default" value="{{ $materi->thumbnail }}">
                                <div class="input-group col-xs-12">
                                    <input type="text" class="form-control file-upload-info" disabled
                                        placeholder="Upload Image">
                                    <span class="input-group-append">
                                        <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                                    </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">Sumber</label>
                                <p class="text-muted font-italic">Jika materi diambil oleh sumber lain, silahkan tuliskan sumber (nama sumber atau link sumber)</p>
                                <input type="text" name="sumber" class="form-control" placeholder="Sumber">
                            </div>
                            <div class="form-group">
                                @error('keterangan')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                                <label for="exampleTextarea1">Keterangan</label>
                                <textarea class="form-control" name="keterangan" placeholder="Isi Ulang Keterangan Materi"  id="exampleTextarea1" rows="4"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
